# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nabita Shrestha
email: contact@nabitashrestha.com
description: All right reserved. &copy; Copyright Nabita Shrestha 2018
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nabitashrestha
github_username: nabitashrestha

social:
  - title: twitter
    url: https://twitter.com/nabita
  - title: facebook
    url: https://facebook.com/nabita
  - title: google-plus
    url: https://plus.google.com/nabita
  - title: instagram
    url: https://instragram.com/nabita
  - title: linkedin
    url: https://linkedin.com/nabita


exclude: [
  "node_modules",
  "gulpfile.js",
  "package.json",
  "package-lock.json"
]

# Build settings
markdown: kramdown
