# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nabita Shrestha
email: contact@nabitashrestha.com
description: All right reserved. &copy; Copyright Nabita Shrestha 2018
  
baseurl: "/nabita" # the subpath of your site, e.g. /blog
url: "https://sawbeanraz.github.io" # the base hostname & protocol for your site
twitter_username: nabitashrestha
github_username: nabitashrestha

social:
  - title: facebook
    url: https://www.facebook.com/nabita.shrestha1/
  - title: instagram
    url: https://www.instagram.com/navy.shrestha1/
  - title: linkedin
    url: https://www.linkedin.com/in/nabita-shrestha-0190a210b/


exclude: [
  "node_modules",
  "gulpfile.js",
  "package.json",
  "package-lock.json"
]

# Build settings
markdown: kramdown
